spring:
  profiles:
    active: build
  devtools:
    restart:
      enabled: false
security:
  user:
    password: password
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      scope: read, write
      auto-approve-scopes: .*
    authorization:
      check-token-access: permitAll()
server:
  port: 8001
  servlet:
    context-path: /demo
