auth-server: http://localhost:8001/auth

server:
  port: 8003
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


