server:
  port: 8001
  servlet:
    context-path: /demo

spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ApolloConfigDB?useSSL=false&characterEncoding=UTF-8
      username: root
      password: root123
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ApolloConfigDB?useSSL=false&characterEncoding=UTF-8
      username: root
      password: root123